export {default as Home } from './Home'
export {default as Auth } from './Auth'
export {default as Products } from './Products'
export {default as Address} from './Address'
export {default as Cart} from './Cart'
export {default as Order} from './Order'
export {default as ProductDetail} from './ProductDetail'
export {default as Search} from './Search'
export {default as UserInfor} from './UserInfor'
export {default as Payment} from './Payment'