// export const API = 'https://backend-travel-thuctap.vercel.app';
export const API = 'http://localhost:5000';
export const LOCAL_STORAGE_TOKEN_NAME = 'NLNE-commerce';

export const SET_AUTH = 'SET_AUTH';

export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_USER_IMAGE = 'UPDATE_USER_IMAGE';

// address
export const CREATE_NEW_ADDRESS = 'CREATE_NEW_ADDRESS';
export const DELETE_ADDRESS = 'DELETE_ADDRESS';
export const UPDATE_ADDRESS_DEFAULT = 'UPDATE_ADDRESS_DEFAULT';

// POST

export const PRODUCTS_LOADED_SUCCESS = 'PRODUCTS_LOADED_SUCCESS';
export const PRODUCTS_LOADED_FAIL = 'PRODUCTS_LOADED_FAIL';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';

// DETAIL
export const DETAILS_LOADED_SUCCESS = 'DETAILS_LOADED_SUCCESS';
export const DETAILS_LOADED_FAIL = 'DETAILS_LOADED_FAIL';
export const CREATE_DETAIL_SUCCESS = 'CREATE_DETAIL_SUCCESS';
export const DELETE_DETAIL_SUCCESS = 'DELETE_DETAIL_SUCCESS';
export const UPDATE_DETAIL_SUCCESS = 'UPDATE_DETAIL_SUCCESS';

// CART
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const ADD_ALL_PRODUCT = 'ADD_ALL_PRODUCT';
export const REMOVE_ALL_PRODUCT = 'ADD_ALL_PRODUCT';
export const SET_TOTAL_AMOUNT = 'TOTAL_AMOUNT';
export const SET_PRODUCT_UPDATE = 'PRODUCT_UPDATE';
